using System.Collections.Generic;
using ClassicUO.Game;
using ClassicUO.IO;

namespace ClassicUO.Network.PacketHandlers;

public delegate void PacketHandler(World world, ref StackDataReader reader);

public static class PacketHandlerRegistry
{
    /// <summary>
    ///     The received-packet handler table: ID, handler, and the handler type's name for diagnostics.
    /// </summary>
    /// <returns>
    ///     A freshly built list, so callers should cache it rather than re-enumerate per packet. IDs are unique,
    ///     but names are not - several IDs share one handler (e.g. 0x16/0x17).
    /// </returns>
    public static IReadOnlyList<(uint Id, PacketHandler Handler, string PacketName)> GetHandlers() =>
    [
        (0x1B, EnterWorld.Receive, nameof(EnterWorld)),
        (0x55, LoginComplete.Receive, nameof(LoginComplete)),
        (0xBD, ClientVersion.Receive, nameof(ClientVersion)),
        (0x03, ClientTalk.Receive, nameof(ClientTalk)),
        (0x0B, Damage.Receive, nameof(Damage)),
        (0x11, CharacterStatus.Receive, nameof(CharacterStatus)),
        (0x15, FollowR.Receive, nameof(FollowR)),
        (0x16, NewHealthBarUpdate.Receive, nameof(NewHealthBarUpdate)),
        (0x17, NewHealthBarUpdate.Receive, nameof(NewHealthBarUpdate)),
        (0x1A, UpdateItem.Receive, nameof(UpdateItem)),
        (0x1C, Talk.Receive, nameof(Talk)),
        (0x1D, DeleteObject.Receive, nameof(DeleteObject)),
        (0x20, UpdatePlayer.Receive, nameof(UpdatePlayer)),
        (0x21, DenyWalk.Receive, nameof(DenyWalk)),
        (0x22, ConfirmWalk.Receive, nameof(ConfirmWalk)),
        (0x23, DragAnimation.Receive, nameof(DragAnimation)),
        (0x24, OpenContainer.Receive, nameof(OpenContainer)),
        (0x25, UpdateContainedItem.Receive, nameof(UpdateContainedItem)),
        (0x27, DenyMoveItem.Receive, nameof(DenyMoveItem)),
        (0x28, EndDraggingItem.Receive, nameof(EndDraggingItem)),
        (0x29, DropItemAccepted.Receive, nameof(DropItemAccepted)),
        (0x2C, DeathScreen.Receive, nameof(DeathScreen)),
        (0x2D, MobileAttributes.Receive, nameof(MobileAttributes)),
        (0x2E, EquipItem.Receive, nameof(EquipItem)),
        (0x2F, Swing.Receive, nameof(Swing)),
        (0x32, Unknown032.Receive, nameof(Unknown032)),
        (0x38, Pathfinding.Receive, nameof(Pathfinding)),
        (0x3A, UpdateSkills.Receive, nameof(UpdateSkills)),
        (0x3B, CloseVendorInterface.Receive, nameof(CloseVendorInterface)),
        (0x3C, UpdateContainedItems.Receive, nameof(UpdateContainedItems)),
        (0x4E, PersonalLightLevel.Receive, nameof(PersonalLightLevel)),
        (0x4F, LightLevel.Receive, nameof(LightLevel)),
        (0x54, PlaySoundEffect.Receive, nameof(PlaySoundEffect)),
        (0x56, MapData.Receive, nameof(MapData)),
        (0x5B, SetTime.Receive, nameof(SetTime)),
        (0x65, SetWeather.Receive, nameof(SetWeather)),
        (0x66, BookData.Receive, nameof(BookData)),
        (0x6C, TargetCursor.Receive, nameof(TargetCursor)),
        (0x6D, PlayMusic.Receive, nameof(PlayMusic)),
        (0x6F, SecureTrading.Receive, nameof(SecureTrading)),
        (0x6E, CharacterAnimation.Receive, nameof(CharacterAnimation)),
        (0x70, GraphicEffect.Receive, nameof(GraphicEffect)),
        (0x71, BulletinBoardData.Receive, nameof(BulletinBoardData)),
        (0x72, Warmode.Receive, nameof(Warmode)),
        (0x73, Ping.Receive, nameof(Ping)),
        (0x74, BuyList.Receive, nameof(BuyList)),
        (0x77, UpdateCharacter.Receive, nameof(UpdateCharacter)),
        (0x78, UpdateObject.Receive, nameof(UpdateObject)),
        (0x7C, OpenMenu.Receive, nameof(OpenMenu)),
        (0x88, OpenPaperdoll.Receive, nameof(OpenPaperdoll)),
        (0x89, CorpseEquipment.Receive, nameof(CorpseEquipment)),
        (0x90, DisplayMap.Receive, nameof(DisplayMap)),
        (0x93, OpenBook.Receive, nameof(OpenBook)),
        (0x95, DyeData.Receive, nameof(DyeData)),
        (0x97, MovePlayer.Receive, nameof(MovePlayer)),
        (0x98, UpdateName.Receive, nameof(UpdateName)),
        (0x99, MultiPlacement.Receive, nameof(MultiPlacement)),
        (0x9A, ASCIIPrompt.Receive, nameof(ASCIIPrompt)),
        (0x9E, SellList.Receive, nameof(SellList)),
        (0xA1, UpdateHitpoints.Receive, nameof(UpdateHitpoints)),
        (0xA2, UpdateMana.Receive, nameof(UpdateMana)),
        (0xA3, UpdateStamina.Receive, nameof(UpdateStamina)),
        (0xA5, OpenUrl.Receive, nameof(OpenUrl)),
        (0xA6, TipWindow.Receive, nameof(TipWindow)),
        (0xAA, AttackCharacter.Receive, nameof(AttackCharacter)),
        (0xAB, TextEntryDialog.Receive, nameof(TextEntryDialog)),
        (0xAF, DisplayDeath.Receive, nameof(DisplayDeath)),
        (0xAE, UnicodeTalk.Receive, nameof(UnicodeTalk)),
        (0xB0, OpenGump.Receive, nameof(OpenGump)),
        (0xB2, ChatMessage.Receive, nameof(ChatMessage)),
        (0xB7, Help.Receive, nameof(Help)),
        (0xB8, CharacterProfile.Receive, nameof(CharacterProfile)),
        (0xB9, EnableLockedFeatures.Receive, nameof(EnableLockedFeatures)),
        (0xBA, DisplayQuestArrow.Receive, nameof(DisplayQuestArrow)),
        (0xBB, UltimaMessengerR.Receive, nameof(UltimaMessengerR)),
        (0xBC, Season.Receive, nameof(Season)),
        (0xBE, AssistVersion.Receive, nameof(AssistVersion)),
        (0xBF, ExtendedCommand.Receive, nameof(ExtendedCommand)),
        (0xC0, GraphicEffect.Receive, nameof(GraphicEffect)),
        (0xC1, DisplayClilocString.Receive, nameof(DisplayClilocString)),
        (0xC2, UnicodePrompt.Receive, nameof(UnicodePrompt)),
        (0xC4, Semivisible.Receive, nameof(Semivisible)),
        (0xC6, InvalidMapEnable.Receive, nameof(InvalidMapEnable)),
        (0xC7, GraphicEffect.Receive, nameof(GraphicEffect)),
        (0xC8, ClientViewRange.Receive, nameof(ClientViewRange)),
        (0xCA, GetUserServerPingGodClientR.Receive, nameof(GetUserServerPingGodClientR)),
        (0xCB, GlobalQueCount.Receive, nameof(GlobalQueCount)),
        (0xCC, DisplayClilocString.Receive, nameof(DisplayClilocString)),
        (0xD0, ConfigurationFileR.Receive, nameof(ConfigurationFileR)),
        (0xD1, Logout.Receive, nameof(Logout)),
        (0xD2, UpdateCharacter.Receive, nameof(UpdateCharacter)),
        (0xD3, UpdateObject.Receive, nameof(UpdateObject)),
        (0xD4, OpenBook.Receive, nameof(OpenBook)),
        (0xD6, MegaCliLoc.Receive, nameof(MegaCliLoc)),
        (0xD7, GenericAOSCommandsR.Receive, nameof(GenericAOSCommandsR)),
        (0xD8, CustomHouse.Receive, nameof(CustomHouse)),
        (0xDB, CharacterTransferLog.Receive, nameof(CharacterTransferLog)),
        (0xDC, OPLInfo.Receive, nameof(OPLInfo)),
        (0xDD, OpenCompressedGump.Receive, nameof(OpenCompressedGump)),
        (0xDE, UpdateMobileStatus.Receive, nameof(UpdateMobileStatus)),
        (0xDF, BuffDebuff.Receive, nameof(BuffDebuff)),
        (0xE2, NewCharacterAnimation.Receive, nameof(NewCharacterAnimation)),
        (0xE3, KREncryptionResponse.Receive, nameof(KREncryptionResponse)),
        (0xE5, DisplayWaypoint.Receive, nameof(DisplayWaypoint)),
        (0xE6, RemoveWaypoint.Receive, nameof(RemoveWaypoint)),
        (0xF0, KrriosClientSpecial.Receive, nameof(KrriosClientSpecial)),
        (0xF1, FreeshardListR.Receive, nameof(FreeshardListR)),
        (0xF3, UpdateItemSA.Receive, nameof(UpdateItemSA)),
        (0xF5, DisplayMap.Receive, nameof(DisplayMap)),
        (0xF6, BoatMoving.Receive, nameof(BoatMoving)),
        (0xF7, PacketList.Receive, nameof(PacketList)),
        (EnhancedPacketHandler.EPID, EnhancedPacketHandler.Handle, nameof(EnhancedPacketHandler)), //For handling custom packets

        // login
        (0xA8, ServerListReceived.Receive, nameof(ServerListReceived)),
        (0x8C, ReceiveServerRelay.Receive, nameof(ReceiveServerRelay)),
        (0x86, UpdateCharacterList.Receive, nameof(UpdateCharacterList)),
        (0xA9, ReceiveCharacterList.Receive, nameof(ReceiveCharacterList)),
        (0x82, ReceiveLoginRejection.Receive, nameof(ReceiveLoginRejection)),
        (0x85, ReceiveLoginRejection.Receive, nameof(ReceiveLoginRejection)),
        (0x53, ReceiveLoginRejection.Receive, nameof(ReceiveLoginRejection)),
        (0xFD, LoginDelay.Receive, nameof(LoginDelay))
    ];
}
