name: TUO-Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (default: legacy)'
        required: true
        default: 'legacy'

env:
  CUO_OUTPUT_PATH: 'bin/dist'
  CUO_PROJECT_PATH: "src/ClassicUO.Client/ClassicUO.Client.csproj"
  BOOTSTRAP: "src/ClassicUO.Bootstrap/src/ClassicUO.Bootstrap.csproj"
  BOOT_OUTPUT_PATH: 'bin/bootstrap'

  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch || github.ref }}

    - name: Get submodules
      run: |
        git config --global url."https://".insteadOf git://
        git submodule update --init --recursive
        
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Build
      run: dotnet publish ${{ env.CUO_PROJECT_PATH }} -c Release -o ${{ env.CUO_OUTPUT_PATH }} -r ${{ matrix.rid }} -p:CustomAssemblyName=TazUO-${{ matrix.rid }}

    - name: Build bootstrapper
      if: matrix.os == 'windows-latest'
      run: dotnet publish ${{ env.BOOTSTRAP }} -c Release -o ${{ env.BOOT_OUTPUT_PATH }}

    - name: Zip build
      shell: bash
      run: |
        cd ${{ env.CUO_OUTPUT_PATH }}
        zip -r ../${{ matrix.rid }}.zip .

    - name: Zip bootstrapper
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd ${{ env.BOOT_OUTPUT_PATH }}
        zip -r ../bootstrap.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tuo-legacy-net9-${{ matrix.rid }}
        path: bin/${{ matrix.rid }}.zip
        retention-days: 30

    - name: Upload Bootstrapper
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: tuo-legacy-net9-bootstrap
        path: bin/bootstrap.zip
        retention-days: 30
