name: TUO-Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (default: dev)'
        required: true
        default: 'dev'

env:
  CUO_OUTPUT_PATH: 'build/dist'
  CUO_PROJECT_PATH: "src/ClassicUO.Client/ClassicUO.Client.csproj"

  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
    outputs:
      rid: ${{ matrix.rid }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Get submodules
        run: |
          git config --global url."https://".insteadOf git://
          git submodule update --init --recursive

      - name: Extract Version
        shell: bash
        id: version
        run: |
          export LC_ALL=C.UTF-8
          VERSION=$(grep -oP '<AssemblyVersion>\K\d+\.\d+\.\d+' src/ClassicUO.Client/ClassicUO.Client.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Build executable
        run: dotnet publish ${{ env.CUO_PROJECT_PATH }} -c Release -o ${{ env.CUO_OUTPUT_PATH }} -r ${{ matrix.rid }}

      - name: Zip build
        shell: bash
        run: |
          mkdir -p flat

          for d in "${{ env.CUO_OUTPUT_PATH }}" "${{ env.CUO_OUTPUT_PATH }}-Lib"; do
            [ -d "$d" ] || continue

            find "$d" \( -name '*.dSYM' -o -name '*.dSYM/' \) -prune -o -type f -print |
            while IFS= read -r file; do
              dest="flat/${file#$d/}"
              mkdir -p "$(dirname "$dest")"
              cp "$file" "$dest"
            done
          done

          cd flat

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pwsh -Command "Compress-Archive -Path * -DestinationPath ../${{ matrix.rid }}.zip -Force"
          else
            zip -r ../${{ matrix.rid }}.zip .
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuo-${{ matrix.rid }}
          path: ${{ matrix.rid }}.zip
          retention-days: 30
